# MakeFile for Gestionnaire_note_calendrier projects

.PHONY: all api dbkv notexa clean

all: api dbkv notexa

api:
	$(MAKE) -C API

dbkv:
	$(MAKE) -C DBKV

notexa:
	$(MAKE) -C Notexa

clean:
	$(MAKE) -C API clean
	$(MAKE) -C DBKV clean
	$(MAKE) -C Notexa clean